version: '3'
services:
  app:
    build:
      context: .
      dockerfile: 'Dockerfile.dev'

    command: rails server -p 3000 -b '0.0.0.0'
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=snapapp_api_dev
    volumes:
      - .:/usr/src
    ports:
      - "3000:3000"
    links:
      - db
  db:
    image: postgres:10.3-alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=snapapp_api_dev
    ports:
      - "5432"
