version: '3'
services:
  app:
    build:
      context: .
      dockerfile: 'Dockerfile.dev'
    depends_on:
      - testdb
    command: ./bin/rails test
    environment:
      - RAILS_ENV=test
      - POSTGRES_HOST=testdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=text_api_test
    volumes:
      - .:/usr/src
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3000:3000"
    links:
      - testdb
  testdb:
    image: postgres:10.3-alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=text_api_dev
    ports:
      - "5432"
